name: Build and Analyze Backend with Maven

on:
  push:
    branches:
      - main  # Set to 'main' or your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze Backend
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build Backend with Maven
      - name: Build Backend with Maven
        working-directory: backend  # Ensure Maven runs in the correct directory
        run: mvn -B clean install --no-transfer-progress

      # SonarQube analysis
      - name: SonarQube Backend Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=your-project-key-backend \
          -Dsonar.host.url=https://sonarcloud.io
