name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-backend:
    name: Build HRVibe Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Backend with Maven
        working-directory: backend
        run: mvn -B clean install --no-transfer-progress

      - name: SonarQube Backend Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=coralee-long_HRVibe-backend \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=coralee-long
        working-directory: backend  # Ensure SonarQube runs in the correct directory


